// Aggregator: runs the whole Gherkin suite (plus the boot smoke test) as a
// SINGLE test target so the app is built and installed once, instead of
// once per feature file.
//
// Each `*_test.dart` here is GENERATED by build_runner from
// integration_test/features/*.feature, so run
//   dart run build_runner build --delete-conflicting-outputs
// before this file will analyze/run. (scripts/integration-report.sh does
// this for you.)
//
// When you add a new .feature, add one import + one main() call below.

import 'app_smoke_test.dart' as smoke;
import 'features/accessibility_test.dart' as accessibility;
import 'features/ad_hoc_driving_test.dart' as ad_hoc_driving;
import 'features/calculations_test.dart' as calculations;
import 'features/drafts_test.dart' as drafts;
import 'features/driving_test.dart' as driving;
import 'features/history_test.dart' as history;
import 'features/home_context_test.dart' as home_context;
import 'features/navigation_test.dart' as navigation;
import 'features/route_management_test.dart' as route_management;
import 'features/seeded_routes_test.dart' as seeded_routes;
import 'features/settings_test.dart' as settings;

void main() {
  smoke.main();
  ad_hoc_driving.main();
  navigation.main();
  seeded_routes.main();
  route_management.main();
  settings.main();
  driving.main();
  history.main();
  home_context.main();
  calculations.main();
  drafts.main();
  accessibility.main();
}
