// Generated by scripts/version.sh — do not edit manually
// ignore_for_file: constant_identifier_names

const String appVersion = '1.0.0-debug+43';
const String appVersionName = '1.0.0-debug';
const int appBuildNumber = 43;
