#!/bin/bash
# Automatic versioning from git tags
# Usage: ./scripts/version.sh
# Sets version in pubspec.yaml and generates lib/app_version.dart

set -e

# Get version from latest git tag (strip leading 'v' if present)
VERSION=$(git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//' || true)
if [ -z "$VERSION" ]; then
  VERSION="1.0.0"
fi

# Build number = total commit count
BUILD=$(git rev-list --count HEAD)

FULL_VERSION="${VERSION}+${BUILD}"

# Update pubspec.yaml
if [[ "$OSTYPE" == "darwin"* ]]; then
  sed -i '' "s/^version: .*/version: ${FULL_VERSION}/" pubspec.yaml
else
  sed -i "s/^version: .*/version: ${FULL_VERSION}/" pubspec.yaml
fi

# Generate Dart version file for runtime access
cat > lib/app_version.dart << EOF
// Generated by scripts/version.sh — do not edit manually
// ignore_for_file: constant_identifier_names

const String appVersion = '${FULL_VERSION}';
const String appVersionName = '${VERSION}';
const int appBuildNumber = ${BUILD};
EOF

echo "Version set to ${FULL_VERSION} (name: ${VERSION}, build: ${BUILD})"
