#!/bin/bash
# Automatic versioning from git tags
# Usage: ./scripts/version.sh [--release|--debug]
#
#   --release   Updates pubspec.yaml and generates lib/app_version.dart
#   --debug     Only generates lib/app_version.dart (with -debug suffix),
#               does not modify pubspec.yaml (safe for hot reload)

set -e

MODE="release"
if [ "$1" = "--debug" ]; then
  MODE="debug"
elif [ "$1" = "--release" ]; then
  MODE="release"
elif [ -n "$1" ]; then
  echo "Usage: $0 [--release|--debug]"
  exit 1
fi

# Get version from latest git tag (strip leading 'v' if present)
VERSION=$(git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//' || true)
if [ -z "$VERSION" ]; then
  VERSION="1.0.0"
fi

# Build number = total commit count
BUILD=$(git rev-list --count HEAD)

if [ "$MODE" = "release" ]; then
  FULL_VERSION="${VERSION}+${BUILD}"
  APP_VERSION="${FULL_VERSION}"
  APP_VERSION_NAME="${VERSION}"

  # Update pubspec.yaml
  if [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i '' "s/^version: .*/version: ${FULL_VERSION}/" pubspec.yaml
  else
    sed -i "s/^version: .*/version: ${FULL_VERSION}/" pubspec.yaml
  fi
else
  # Debug: don't touch pubspec.yaml, use -debug suffix for display
  APP_VERSION="${VERSION}-debug+${BUILD}"
  APP_VERSION_NAME="${VERSION}-debug"
fi

# Generate Dart version file for runtime access
cat > lib/app_version.dart << EOF
// Generated by scripts/version.sh — do not edit manually
// ignore_for_file: constant_identifier_names

const String appVersion = '${APP_VERSION}';
const String appVersionName = '${APP_VERSION_NAME}';
const int appBuildNumber = ${BUILD};
EOF

echo "Version set to ${APP_VERSION} (name: ${APP_VERSION_NAME}, build: ${BUILD}, mode: ${MODE})"
